import mongoose from "mongoose";
import dotenv from "dotenv";
import Restaurant from "../models/restaurant.js";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../config/config.env") });

const firstNames = ["Aarav", "Vihaan", "Aditya", "Arjun", "Sai", "Krishna", "Ishaan", "Shaurya", "Rudra", "Om", "Aadhya", "Diya", "Kashvi", "Saanvi", "Myra", "Riya", "Ananya", "Aarohi", "Navya", "Kiara"];
const lastNames = ["Sharma", "Patel", "Singh", "Kumar", "Das", "Bose", "Gupta", "Verma", "Reddy", "Nair", "Rao", "Joshi", "Iyer", "Pillai", "Chauhan"];

const positiveComments = [
  "Absolutely loved the food! Will definitely order again.",
  "Great taste and fast delivery. Highly recommended.",
  "The spices were just perfect. Authentic taste.",
  "Really good portion sizes and it was still hot when it arrived.",
  "My new favorite spot for dinner. Everything was fresh.",
  "Delicious! The best I've had in a long time.",
  "Excellent packaging and the taste was top notch.",
  "Very flavorful and rich. The chef really knows what they are doing.",
  "Superb quality for the price.",
  "Amazing experience. The food was simply outstanding."
];

const neutralComments = [
  "It was decent, nothing too special but good enough.",
  "Food was okay, but the delivery took a bit too long.",
  "Average taste. Might try something else next time.",
  "Not bad, but I've had better from similar places.",
  "It was alright. The portion could have been bigger.",
  "Standard fare. Good for a quick meal.",
  "A bit too oily for my liking, but the flavors were okay.",
  "Satisfactory. The packaging was a bit flimsy though."
];

const negativeComments = [
  "Really disappointed. The food was cold and tasteless.",
  "Too spicy and the meat was overcooked.",
  "Would not recommend. The quality has really gone down.",
  "Very small portions for what they charge. Total rip off.",
  "Terrible experience. The food arrived very late and was soggy.",
  "Not authentic at all. Very bland.",
  "Complete waste of money. Could not even finish it.",
  "Missing items from my order and the rest was just bad."
];

function getRandomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateRandomReview() {
  const name = `${getRandomItem(firstNames)} ${getRandomItem(lastNames)}`;
  
  // Decide the sentiment to pick a rating and comment
  const sentimentRoll = Math.random();
  let rating, comment;
  
  if (sentimentRoll > 0.6) {
    // 40% chance of Positive (4 or 5)
    rating = Math.random() > 0.5 ? 5 : 4;
    comment = getRandomItem(positiveComments);
  } else if (sentimentRoll > 0.3) {
    // 30% chance of Neutral (3)
    rating = 3;
    comment = getRandomItem(neutralComments);
  } else {
    // 30% chance of Negative (1 or 2)
    rating = Math.random() > 0.5 ? 2 : 1;
    comment = getRandomItem(negativeComments);
  }

  return { name, rating, Comment: comment };
}

const seedReviews = async () => {
  try {
    const uri = process.env.DB_LOCAL_URI || process.env.DB_URI;
    console.log("Connecting to Database:", uri);
    await mongoose.connect(uri);

    const restaurants = await Restaurant.find();
    console.log(`Found ${restaurants.length} restaurants to update...`);

    let updatedCount = 0;

    for (let restaurant of restaurants) {
      // Random number between 3 and 10
      const numReviewsToGenerate = Math.floor(Math.random() * 8) + 3;
      
      const newReviews = [];
      for (let i = 0; i < numReviewsToGenerate; i++) {
        newReviews.push(generateRandomReview());
      }

      // Calculate new ratings
      const totalRatings = newReviews.reduce((acc, item) => acc + item.rating, 0);
      const avgRating = totalRatings / newReviews.length;

      restaurant.reviews = newReviews;
      restaurant.numOfReviews = newReviews.length;
      restaurant.ratings = Number(avgRating.toFixed(1));
      
      // Clear AI insights so they can be regenerated by the user
      restaurant.reviewSentiment = undefined;
      restaurant.reviewSummaryBullets = [];
      restaurant.reviewTopMentions = [];

      await restaurant.save({ validateBeforeSave: false });
      updatedCount++;
    }

    console.log(`Successfully added realistic reviews to ${updatedCount} restaurants!`);
    process.exit();
  } catch (error) {
    console.error("Error seeding reviews:", error);
    process.exit(1);
  }
};

seedReviews();
